# Generated by Django 3.2.12 on 2022-02-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('task', models.CharField(max_length=255)),
                ('collect_amount', models.FloatField()),
                ('numbersOfCase', models.FloatField()),
                ('status', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=512)),
                ('taskStatus', models.CharField(max_length=100)),
                ('staffName', models.CharField(max_length=100)),
            ],
        ),
    ]
