# Generated by Django 3.2.12 on 2022-03-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0002_tasksheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksheet',
            name='taskStatus',
            field=models.BooleanField(default=True),
        ),
    ]
