# Generated by Django 3.2.12 on 2022-03-01 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0005_tasksheet_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksheet',
            name='otp',
        ),
    ]
