# Generated by Django 3.2.12 on 2022-03-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0007_staff_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksheet',
            name='numbersOfCase',
            field=models.IntegerField(),
        ),
    ]
