# Generated by Django 3.2.12 on 2022-03-01 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0010_dailyfileattach_taskstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyFileAttach',
        ),
    ]
