# Generated by Django 3.2.12 on 2022-03-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0011_delete_dailyfileattach'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFileAttach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_file', models.FileField(blank=True, null=True, upload_to='media/Daily File/', verbose_name='file')),
                ('remark', models.CharField(blank=True, max_length=1024, null=True)),
                ('taskStatus', models.BooleanField(default=True)),
                ('staffName', models.CharField(max_length=100)),
            ],
        ),
    ]
