# Generated by Django 3.2.12 on 2022-03-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0013_weeklyfileattach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyfileattach',
            name='type_file',
            field=models.FileField(blank=True, null=True, upload_to='media/Weekly File/', verbose_name='file'),
        ),
    ]
