# Generated by Django 3.2.12 on 2022-03-03 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0015_tasksheet_staff_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyfileattach',
            name='staff_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_panel.staff'),
        ),
        migrations.AddField(
            model_name='weeklyfileattach',
            name='staff_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_panel.staff'),
        ),
    ]
