# Generated by Django 3.2.12 on 2022-03-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0016_auto_20220303_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='ssa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
