# Generated by Django 3.2.12 on 2022-03-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0017_auto_20220303_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='csc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
