# Generated by Django 3.2.12 on 2022-03-04 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0018_staff_csc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksheet',
            name='task',
        ),
    ]
