# Generated by Django 3.2.12 on 2022-03-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0019_remove_tasksheet_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksheet',
            name='CBPValue',
            field=models.IntegerField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='tasksheet',
            name='C_topValue',
            field=models.IntegerField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='tasksheet',
            name='MNP_SIM',
            field=models.IntegerField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='tasksheet',
            name='biometricAadhar',
            field=models.IntegerField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='tasksheet',
            name='mandatoryAadhar',
            field=models.IntegerField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='tasksheet',
            name='newAadhar',
            field=models.IntegerField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='tasksheet',
            name='pairedSim',
            field=models.IntegerField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='tasksheet',
            name='updateAadhar',
            field=models.IntegerField(default=0, max_length=255),
        ),
    ]
