# Generated by Django 3.2.12 on 2022-03-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0022_auto_20220304_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksheet',
            name='CBPValue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasksheet',
            name='C_topValue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasksheet',
            name='MNP_SIM',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasksheet',
            name='biometricAadhar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasksheet',
            name='mandatoryAadhar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasksheet',
            name='newAadhar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasksheet',
            name='pairedSim',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasksheet',
            name='updateAadhar',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
