# Generated by Django 3.2.12 on 2022-03-04 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0023_auto_20220304_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='funds',
            name='staff_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_panel.staff'),
        ),
    ]
