# Generated by Django 3.2.12 on 2022-03-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0024_funds_staff_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='funds',
            name='staffName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
