# Generated by Django 3.2.12 on 2022-03-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0025_funds_staffname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
