# Generated by Django 3.2.12 on 2022-03-08 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0028_alter_staff_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppData',
        ),
        migrations.RemoveField(
            model_name='dailyfileattach',
            name='staff_key',
        ),
        migrations.RemoveField(
            model_name='funds',
            name='staff_key',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.RemoveField(
            model_name='tasksheet',
            name='staff_key',
        ),
        migrations.RemoveField(
            model_name='weeklyfileattach',
            name='staff_key',
        ),
        migrations.DeleteModel(
            name='DailyFileAttach',
        ),
        migrations.DeleteModel(
            name='Funds',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='TaskSheet',
        ),
        migrations.DeleteModel(
            name='WeeklyFileAttach',
        ),
    ]
