# Generated by Django 3.2.12 on 2022-03-08 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_panel', '0029_auto_20220308_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=10, null=True)),
                ('otp', models.CharField(default=359, max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ssa', models.CharField(blank=True, max_length=255, null=True)),
                ('csc', models.CharField(blank=True, max_length=255, null=True)),
                ('joining_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ssa', models.CharField(blank=True, max_length=255, null=True)),
                ('csc', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('newEnrollment', models.IntegerField(blank=True, null=True)),
                ('AadharMandatoryUpdate', models.IntegerField(blank=True, null=True)),
                ('AadharDemographicUpdate', models.IntegerField(blank=True, null=True)),
                ('AadharBiometricUpdate', models.IntegerField(blank=True, null=True)),
                ('remark', models.CharField(max_length=512)),
                ('taskStatus', models.BooleanField(default=True)),
                ('staff_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_panel.staff')),
            ],
        ),
        migrations.CreateModel(
            name='DailyCashReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ssa', models.CharField(blank=True, max_length=255, null=True)),
                ('csc', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('aadharCash', models.FloatField(blank=True, null=True)),
                ('CBPcash', models.FloatField(blank=True, null=True)),
                ('C_TopCash', models.FloatField(blank=True, null=True)),
                ('NormalSimCash', models.FloatField(blank=True, null=True)),
                ('MnpSimCash', models.FloatField(blank=True, null=True)),
                ('SwappingSimCash', models.FloatField(blank=True, null=True)),
                ('PostpaidSimCash', models.FloatField(blank=True, null=True)),
                ('DailyTotalCollection', models.FloatField(blank=True, null=True)),
                ('opeingCashBalance', models.FloatField(blank=True, null=True)),
                ('cashInHand', models.FloatField(blank=True, null=True)),
                ('bankDeposite', models.FloatField(blank=True, null=True)),
                ('staff_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_panel.staff')),
            ],
        ),
        migrations.CreateModel(
            name='DailyBsnlWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ssa', models.CharField(blank=True, max_length=255, null=True)),
                ('csc', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('CBPsales', models.FloatField(blank=True, null=True)),
                ('C_TopRechageSales', models.FloatField(blank=True, null=True)),
                ('C_TopFrcSales', models.FloatField(blank=True, null=True)),
                ('NormalSimSale', models.IntegerField(blank=True, null=True)),
                ('MnpSimSale', models.IntegerField(blank=True, null=True)),
                ('SwappingSimSale', models.IntegerField(blank=True, null=True)),
                ('PostpaidSimSale', models.IntegerField(blank=True, null=True)),
                ('staff_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_panel.staff')),
            ],
        ),
    ]
