# Generated by Django 3.2.12 on 2022-03-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0030_appdata_dailybsnlwork_dailycashreport_staff_tasksheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
