# Generated by Django 3.2.12 on 2022-03-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0031_auto_20220308_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailybsnlwork',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='dailycashreport',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='tasksheet',
            name='session_id',
        ),
        migrations.AddField(
            model_name='dailybsnlwork',
            name='station_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dailycashreport',
            name='station_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tasksheet',
            name='station_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
