# Generated by Django 3.2.12 on 2022-03-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0032_auto_20220308_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='session_id',
        ),
        migrations.AddField(
            model_name='staff',
            name='station_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
