# Generated by Django 3.2.12 on 2022-03-09 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0037_depositecash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ssa', models.CharField(blank=True, max_length=255, null=True)),
                ('csc', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('chequeNo', models.CharField(max_length=255)),
                ('chaqueDate', models.DateField()),
                ('lan_phoNo', models.CharField(blank=True, max_length=12, null=True)),
                ('amount', models.FloatField(max_length=255)),
                ('challanNumber', models.CharField(max_length=255)),
                ('personCollectingCheque', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_panel.staff')),
            ],
        ),
    ]
