# Generated by Django 3.2.12 on 2022-03-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0039_auto_20220310_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailybsnlwork',
            name='HTMLFile',
        ),
        migrations.AddField(
            model_name='tasksheet',
            name='HTMLFile',
            field=models.FileField(blank=True, null=True, upload_to='media/aadharwork/', verbose_name='file'),
        ),
    ]
