# Generated by Django 3.2.12 on 2022-03-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0041_aadharportalcashreport_htmlfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadharportalcashreport',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
