# Generated by Django 3.2.12 on 2022-03-10 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0042_aadharportalcashreport_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AadharPortalCashReport',
        ),
    ]
