# Generated by Django 3.2.12 on 2022-03-10 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0044_portalcashreport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortalCashReport',
            new_name='AadharPortalCashReport',
        ),
    ]
