# Generated by Django 3.2.12 on 2022-03-10 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0048_auto_20220310_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='ssa',
        ),
        migrations.AddField(
            model_name='staff',
            name='ssavalue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_panel.ssavalue'),
        ),
    ]
