# Generated by Django 3.2.12 on 2022-03-11 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0049_auto_20220310_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='ssavalue',
        ),
    ]
