# Generated by Django 3.2.12 on 2022-03-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0051_auto_20220311_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='station_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
