# Generated by Django 3.2.12 on 2022-03-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0052_stock_station_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
