# Generated by Django 3.2.12 on 2022-03-15 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0053_stock_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_panel.city'),
        ),
    ]
