# Generated by Django 3.2.12 on 2022-03-15 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0055_stock_ssavalue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='ssavalue',
            new_name='ssa',
        ),
    ]
