# Generated by Django 3.2.12 on 2022-03-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0057_auto_20220315_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aadharportalcashreport',
            name='city',
        ),
        migrations.AddField(
            model_name='aadharportalcashreport',
            name='csc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aadharportalcashreport',
            name='ssa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
