# Generated by Django 3.2.12 on 2022-03-15 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0058_auto_20220315_1217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AadharPortalCashReport',
        ),
    ]
