# Generated by Django 3.2.12 on 2022-03-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0062_auto_20220315_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aadharportalcashreport',
            name='city',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='city',
        ),
        migrations.RemoveField(
            model_name='chequedetail',
            name='city',
        ),
        migrations.RemoveField(
            model_name='dailybsnlwork',
            name='city',
        ),
        migrations.RemoveField(
            model_name='dailycashreport',
            name='city',
        ),
        migrations.RemoveField(
            model_name='depositecash',
            name='city',
        ),
        migrations.AddField(
            model_name='aadharportalcashreport',
            name='csc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='csc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chequedetail',
            name='csc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dailybsnlwork',
            name='csc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dailycashreport',
            name='csc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='depositecash',
            name='csc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aadharportalcashreport',
            name='ssa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='ssa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chequedetail',
            name='ssa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dailybsnlwork',
            name='ssa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dailycashreport',
            name='ssa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='depositecash',
            name='ssa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
