# Generated by Django 3.2.12 on 2022-03-15 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0063_auto_20220315_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('CBPValue', models.IntegerField(blank=True, null=True)),
                ('C_TopValue', models.IntegerField(blank=True, null=True)),
                ('station_id', models.CharField(blank=True, max_length=255, null=True)),
                ('NormalSimSale', models.IntegerField(blank=True, null=True)),
                ('MnpSim', models.IntegerField(blank=True, null=True)),
                ('Swapping', models.IntegerField(blank=True, null=True)),
                ('PostpaidSim', models.IntegerField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_panel.city')),
                ('ssa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_panel.ssavalue')),
                ('staff_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_panel.staff')),
            ],
        ),
    ]
