# Generated by Django 3.2.12 on 2022-03-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0064_stockupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybsnlwork',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailycashreport',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasksheet',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockupdate',
            name='CBPValue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockupdate',
            name='C_TopValue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockupdate',
            name='NormalSimSale',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
