# Generated by Django 3.2.12 on 2022-03-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0065_auto_20220315_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadharportalcashreport',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chequedetail',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
