# Generated by Django 3.2.12 on 2022-03-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0066_auto_20220315_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockupdate',
            name='NormalSimSale',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
