# Generated by Django 3.2.12 on 2022-03-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0069_auto_20220324_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksheet',
            name='machine_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
