# Generated by Django 3.2.12 on 2022-04-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0070_tasksheet_machine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='HODEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='machine_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
