# Generated by Django 3.2.12 on 2022-04-07 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0073_auto_20220406_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='mailSendReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ssa', models.CharField(blank=True, max_length=255, null=True)),
                ('csc', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('staff_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_panel.staff')),
            ],
        ),
    ]
